checksumBehavior: update

nodeLinker: node-modules

npmScopes:
  goatjs:
    npmAlwaysAuth: true
    npmRegistryServer: "https://europe-west8-npm.pkg.dev/open-gto-2/goat/"

plugins:
  - checksum: cd785c929954ba6e28a102cfc09d7cefaac12fe84a806d6c66f9176530e4b134a8b50a7c6d82f4e72ee8a16c4a3977162b637c8f61337110e04ebd9cb9ae5679
    path: .yarn/plugins/@yarnpkg/plugin-gcp-auth.cjs
    spec: "https://github.com/AndyClausen/yarn-plugin-gcp-auth/releases/latest/download/plugin-gcp-auth.js"
